# Generated by Django 3.2.7 on 2021-09-25 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_mgm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
